### ISSUE TITLE
New build warning

### ISSUE THREAD

**Issue by anjohnson** [epics-base/pvaClientCPP#17]
@mrkraimer 

Your last merge to pvaClientCPP introduced this annoying compiler warning because you deleted the class virtual destructor:

pv/pvaClient.h:1259: warning: 'class epics::pvaClient::PvaClientMonitorRequester' has virtual functions but non-virtual destructor

The class has at least one virtual member function; please reintroduce the virtual destructor:
    http://stackoverflow.com/questions/461203/when-to-use-virtual-destructors

Thanks,

- Andrew

**Comment by mrkraimer** [comment]
Fixed and merged
