### ISSUE TITLE
API Unification suggestion

### ISSUE THREAD

**Issue by anjohnson** [epics-base/pvaClientCPP#4]
Rename PvaClientGetData::getBitSet() and PvaClientPutData::getBitSet() to match PvaClientMonitorData::getChangedBitSet(). All 3 classes already have a showChanged() method so there is already precedent to used "Changed" in the method names for those classes.

**Comment by mrkraimer** [comment]
This is already done in pvaClientJava.
It will be done in pvaClientCPP while making other changes resulting from experience gained while implementing pvaClientJava.

**Comment by mrkraimer** [comment]
Rename has been implemented for both CPP and Java
