### ISSUE TITLE
Scalar Array Put Into Fields Not Named "value" 

### ISSUE THREAD

**Issue by sveseli** [epics-base/pvaClientCPP#53]
At the moment one cannot separately update (via request descriptor) scalar array fields that are not called "value". The checkValue() call in putStringArray() function shown below rejects such puts. Similar problem occurs in multiple places in the PvaClientPutData class.

void PvaClientPutData::putStringArray(shared_vector<const std::string>
const & value)
{
      checkValue();
      PVStringArrayPtr pv = pvStructure->getSubField<PVStringArray>("value");
      if(!pv) {
          throw std::runtime_error(messagePrefix + notStringArray);
      }
      pv->replace(value);
}

**Comment by mrkraimer** [comment]
I agree that should work on any field that is a scalarArray.
Same for putString, putDouble, putDoubleArray, getString, getDouble, getStringArray,getDoubleArray.

**Comment by mrkraimer** [comment]
This caused more changes than I thought.
I really had the name "value" as an integral part of getDouble, putDouble, etc.
I made major changes to the PvaClient*Data implementation.
But with 200+ LESS lines of code and satisfying this issue
I still want to make  few changes and also update doc.


But if you want to try it, the new code is in:
[pvaClientCPP]( https://github.com/mrkraimer/pvaClientCPP)

Marty

**Comment by mrkraimer** [comment]
I spoke to soon.
It does not work properly.

**Comment by mrkraimer** [comment]
pull request #55 addresses this issue
